package com.k9sv.domain.pojo;
// Generated 2013-3-5 1:50:15 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Album generated by hbm2java
 */
public class Album  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 2658035266996567464L;
	private short id;
     private String name;
     private String dogId;
     private String content;
     private Date created;
     private Date updated;
     private int viewCount;

    public Album() {
    }

	
    public Album(String name, String dogId) {
        this.name = name;
        this.dogId = dogId;
    }
    public Album(String name, String dogId, String content, Date created, Date updated, int viewCount) {
       this.name = name;
       this.dogId = dogId;
       this.content = content;
       this.created = created;
       this.updated = updated;
       this.viewCount = viewCount;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDogId() {
        return this.dogId;
    }
    
    public void setDogId(String dogId) {
        this.dogId = dogId;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public int getViewCount() {
        return this.viewCount;
    }
    
    public void setViewCount(int viewCount) {
        this.viewCount = viewCount;
    }




}


