package com.k9sv.domain.pojo;

// Generated 2013-3-5 1:50:15 by Hibernate Tools 3.6.0

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2792415952843312770L;
	private int id;
	private String name;
	private int type;
	private int pid;
	
	private City city;

	public City() {
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public int getPid() {
		return pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public City getCity() {
		return city;
	}

	public void setCity(City city) {
		this.city = city;
	}

}
