package com.k9sv.domain.pojo;

// Generated 2013-3-5 1:50:15 by Hibernate Tools 3.6.0

import java.util.Date;

import com.k9sv.Config2;
import com.k9sv.util.DateUtil;
import com.k9sv.util.StringUtil;

/**
 * Dog generated by hbm2java
 */
@SuppressWarnings("unused")
public class Dog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8809886082009020253L;
	private int id;
	private int categoryId;// 犬种
	private String blood;// 血统证书
	private String earNo; // 耳号
	private int sex; // 性别 0 母犬，1 公犬
	private String name; // 名称
	private String intro;// 介绍
	private String fatherBlood; // 父亲血统证书
	private String matherBlood; // 母亲血统证书
	private Date birthday; // 出生日期
	private String birthdayStr;
	private String avatar; // 图片
	private String avatarStr;
	private Float height; // 肩高
	private Float weight; // 体重
	private int ownerId;// 拥有人
	private int sireId;// 繁殖人
	private int status;// 状态 0 全显示 1只能修改名字
	private int viewed;// 浏览次数
	private int zan;// 被赞次数
	private int commentCount;// 评论次数
	private int favoriteCount;// 收藏数量
	private Date created;
	private String createdStr;
	private int deleted;
	private String chip;// 芯片号
	private int classify;// 宠物种类 0狗1猫2其他

	private int command;// 0 普通，1推荐，2推荐到首页

	private Date updated;

	private Profile owner;

	private Profile sire;

	private String sbirthday;

	private Category category;

	private String photo;

	private int isok;

	public String getPhoto() {
		return avatar.replace("x", "");
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public int getCommand() {
		return command;
	}

	public void setCommand(int command) {
		this.command = command;
	}

	public int getCategoryId() {
		return categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public String getBlood() {
		return blood;
	}

	public void setBlood(String blood) {
		this.blood = blood;
	}

	public String getEarNo() {
		return earNo;
	}

	public void setEarNo(String earNo) {
		this.earNo = earNo;
	}

	public int getSex() {
		return sex;
	}

	public void setSex(int sex) {
		this.sex = sex;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIntro() {
		return intro;
	}

	public void setIntro(String intro) {
		this.intro = intro;
	}

	public String getFatherBlood() {
		return fatherBlood;
	}

	public void setFatherBlood(String fatherBlood) {
		this.fatherBlood = fatherBlood;
	}

	public String getMatherBlood() {
		return matherBlood;
	}

	public void setMatherBlood(String matherBlood) {
		this.matherBlood = matherBlood;
	}

	public Date getBirthday() {
		return birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getAvatar() {
		return avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	public float getHeight() {
		return height;
	}

	public void setHeight(float height) {
		this.height = height;
	}

	public float getWeight() {
		return weight;
	}

	public void setWeight(float weight) {
		this.weight = weight;
	}

	public int getOwnerId() {
		return ownerId;
	}

	public void setOwnerId(int ownerId) {
		this.ownerId = ownerId;
	}

	public int getSireId() {
		return sireId;
	}

	public void setSireId(int sireId) {
		this.sireId = sireId;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getViewed() {
		return viewed;
	}

	public void setViewed(int viewed) {
		this.viewed = viewed;
	}

	public int getZan() {
		return zan;
	}

	public void setZan(int zan) {
		this.zan = zan;
	}

	public int getCommentCount() {
		return commentCount;
	}

	public void setCommentCount(int commentCount) {
		this.commentCount = commentCount;
	}

	public int getFavoriteCount() {
		return favoriteCount;
	}

	public void setFavoriteCount(int favoriteCount) {
		this.favoriteCount = favoriteCount;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public Profile getOwner() {
		return owner;
	}

	public void setOwner(Profile owner) {
		this.owner = owner;
	}

	public Profile getSire() {
		return sire;
	}

	public void setSire(Profile sire) {
		this.sire = sire;
	}

	public String getSbirthday() {
		return sbirthday;
	}

	public void setSbirthday(String sbirthday) {
		this.sbirthday = sbirthday;
	}

	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public int getDeleted() {
		return deleted;
	}

	public void setDeleted(int deleted) {
		this.deleted = deleted;
	}

	public String getCreatedStr() {
		return DateUtil.getFormatDateTime(this.created, "yyyy-MM-dd");
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getChip() {
		return chip;
	}

	public void setChip(String chip) {
		this.chip = chip;
	}

	public int getClassify() {
		return classify;
	}

	public void setClassify(int classify) {
		this.classify = classify;
	}

	public int getIsok() {
		return isok;
	}

	public void setIsok(int isok) {
		this.isok = isok;
	}

	public String getBirthdayStr() {
		return DateUtil.getFormatDateTime(this.birthday, "yyyy-MM-dd");
	}

	public String getAvatarStr() {
		if (StringUtil.isNotEmpty(this.avatar)) {
			if (this.avatar.startsWith("http")) {
				this.avatarStr = this.avatar;
			} else {
				this.avatarStr = Config2.AvatarImgServer + this.avatar;
			}
		}
		return avatarStr;
	}
}
