package com.k9sv.domain.pojo;
// Generated 2013-3-5 1:50:15 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Photo generated by hbm2java
 */
@SuppressWarnings("unused")
public class DogPhoto  implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 55607901889643825L;
	private int id;
	private String title;
	private String content;
	private int dogId;
	private int uid;
	private String url;
	private Date created;
	private int viewed;
	private int good;
	private int replied;
	private Dog dog;
	private String photo;
	
	public String getPhoto() {
		return url.replace("x", "");
	}
	public void setPhoto(String photo) {
		this.photo = photo;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public int getDogId() {
		return dogId;
	}
	public void setDogId(int dogId) {
		this.dogId = dogId;
	}
	public int getUid() {
		return uid;
	}
	public void setUid(int uid) {
		this.uid = uid;
	}
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	public Date getCreated() {
		return created;
	}
	public void setCreated(Date created) {
		this.created = created;
	}
	public int getViewed() {
		return viewed;
	}
	public void setViewed(int viewed) {
		this.viewed = viewed;
	}
	public int getGood() {
		return good;
	}
	public void setGood(int good) {
		this.good = good;
	}
	public int getReplied() {
		return replied;
	}
	public void setReplied(int replied) {
		this.replied = replied;
	}
	public Dog getDog() {
		return dog;
	}
	public void setDog(Dog dog) {
		this.dog = dog;
	}
}


