package com.k9sv.domain.pojo;
// Generated 2013-3-5 1:50:15 by Hibernate Tools 3.6.0



/**
 * Ip generated by hbm2java
 */
public class Ip  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -8426673275147945565L;
	private int id;
     private double start_ip;
     private double end_ip;
     private String province;
     private String city;
     private String isp;
     private int city_id;

    public Ip() {
    }

	
    public Ip(double start_ip, double end_ip, String province) {
        this.start_ip = start_ip;
        this.end_ip = end_ip;
        this.province = province;
    }
    public Ip(double start_ip, double end_ip, String province, String city, String isp, int city_id) {
       this.start_ip = start_ip;
       this.end_ip = end_ip;
       this.province = province;
       this.city = city;
       this.isp = isp;
       this.city_id = city_id;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public double getStart_ip() {
        return this.start_ip;
    }
    
    public void setStart_ip(double start_ip) {
        this.start_ip = start_ip;
    }
    public double getEnd_ip() {
        return this.end_ip;
    }
    
    public void setEnd_ip(double end_ip) {
        this.end_ip = end_ip;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getIsp() {
        return this.isp;
    }
    
    public void setIsp(String isp) {
        this.isp = isp;
    }
    public int getCity_id() {
        return this.city_id;
    }
    
    public void setCity_id(int city_id) {
        this.city_id = city_id;
    }




}


