package com.k9sv.domain.pojo;

import java.util.Date;

import com.k9sv.Config2;
import com.k9sv.util.DateUtil;
import com.k9sv.util.StringUtil;

/**
 * Profile generated by hbm2java
 */
public class Profile implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2707826210141247374L;
	private int id;
	private Account account;
	private int sex;
	private String trueName;
	private String nickName;
	private String email;
	private String mobile;
	private String telephone;
	private String qq;
	private String avatar;
	private String avatarStr;
	private int feedsCount;
	private int topicsCount;
	private int friendsCount;
	private int viewCount;
	private int level;
	private int score;
	private int prestige;
	private int goldCount;
	private String domain;
	private String intro;
	private String company;
	private String address;
	private String IDcard;
	private int cityId;
	private City city;
	private Role role;
	private int isCity;
	private int fromId;
	private float latitude;
	private float longtitude;
	private Date birthday;
	@SuppressWarnings("unused")
	private String birthdayStr;
	private int roleId;
	private String topicPic;

	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final Profile other = (Profile) obj;
		if (this.getId() != other.getId())
			return false;
		return true;
	}

	public int hashCode() {
		return id;
	}

	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public int getRoleId() {
		return roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getSex() {
		return sex;
	}

	public void setSex(int sex) {
		this.sex = sex;
	}

	public String getTrueName() {
		return trueName;
	}

	public void setTrueName(String trueName) {
		this.trueName = trueName;
	}

	public String getNickName() {
		return nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getQq() {
		return qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getAvatar() {
		return avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	public String getDomain() {
		return domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public String getIntro() {
		return intro;
	}

	public void setIntro(String intro) {
		this.intro = intro;
	}

	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getIDcard() {
		return IDcard;
	}

	public void setIDcard(String iDcard) {
		IDcard = iDcard;
	}

	public int getCityId() {
		return cityId;
	}

	public void setCityId(int cityId) {
		this.cityId = cityId;
	}

	public City getCity() {
		return city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public int getIsCity() {
		return isCity;
	}

	public void setIsCity(int isCity) {
		this.isCity = isCity;
	}

	public float getLatitude() {
		return latitude;
	}

	public void setLatitude(float latitude) {
		this.latitude = latitude;
	}

	public float getLongtitude() {
		return longtitude;
	}

	public void setLongtitude(float longtitude) {
		this.longtitude = longtitude;
	}

	public Date getBirthday() {
		return birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public int getFeedsCount() {
		return feedsCount;
	}

	public void setFeedsCount(int feedsCount) {
		this.feedsCount = feedsCount;
	}

	public int getTopicsCount() {
		return topicsCount;
	}

	public void setTopicsCount(int topicsCount) {
		this.topicsCount = topicsCount;
	}

	public int getFriendsCount() {
		return friendsCount;
	}

	public void setFriendsCount(int friendsCount) {
		this.friendsCount = friendsCount;
	}

	public int getViewCount() {
		return viewCount;
	}

	public void setViewCount(int viewCount) {
		this.viewCount = viewCount;
	}

	public int getLevel() {
		return level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public int getScore() {
		return score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	public int getPrestige() {
		return prestige;
	}

	public void setPrestige(int prestige) {
		this.prestige = prestige;
	}

	public String getBirthdayStr() {
		try {
			return DateUtil.getFormatDateTime(birthday, "yyyy-MM-dd");
		} catch (Exception e) {
			return null;
		}

	}

	public int getGoldCount() {
		return goldCount;
	}

	public void setGoldCount(int goldCount) {
		this.goldCount = goldCount;
	}

	public String getTopicPic() {
		return topicPic;
	}

	public void setTopicPic(String topicPic) {
		this.topicPic = topicPic;
	}

	public String getAvatarStr() {
		if (StringUtil.isNotEmpty(this.avatar)) {
			if (this.avatar.startsWith("http")) {
				this.avatarStr = this.avatar;
			} else {
				String avatar = this.avatar + "!avatar134";
				this.avatarStr = Config2.AvatarImgServer + avatar;
			}

		}
		return avatarStr;
	}

	public int getFromId() {
		return fromId;
	}

	public void setFromId(int fromId) {
		this.fromId = fromId;
	}

}
