package com.k9sv.domain.pojo;
// Generated 2013-3-5 1:50:15 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ShowDog generated by hbm2java
 */
public class ShowDog  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -2280889060654718001L;
	private int id;
     private String dogId;
     private Integer showId;
     private String avatar;
     private String content;
     private String video;
     private Integer status;
     private Date created;
     private Integer colorScore;
     private Integer sportScore;
     private Integer boneScore;
     private Integer bodyScore;
     private Integer headScore;
     private Integer cleverScore;
     private Dog dog;

    public ShowDog() {
    }

    public ShowDog(String dogId, Integer showId, String avatar, String content, String video, Integer status, Date created, Integer colorScore, Integer sportScore, Integer boneScore, Integer bodyScore, Integer headScore, Integer cleverScore, Dog dog) {
       this.dogId = dogId;
       this.showId = showId;
       this.avatar = avatar;
       this.content = content;
       this.video = video;
       this.status = status;
       this.created = created;
       this.colorScore = colorScore;
       this.sportScore = sportScore;
       this.boneScore = boneScore;
       this.bodyScore = bodyScore;
       this.headScore = headScore;
       this.cleverScore = cleverScore;
       this.dog = dog;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDogId() {
        return this.dogId;
    }
    
    public void setDogId(String dogId) {
        this.dogId = dogId;
    }
    public Integer getShowId() {
        return this.showId;
    }
    
    public void setShowId(Integer showId) {
        this.showId = showId;
    }
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getVideo() {
        return this.video;
    }
    
    public void setVideo(String video) {
        this.video = video;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Integer getColorScore() {
        return this.colorScore;
    }
    
    public void setColorScore(Integer colorScore) {
        this.colorScore = colorScore;
    }
    public Integer getSportScore() {
        return this.sportScore;
    }
    
    public void setSportScore(Integer sportScore) {
        this.sportScore = sportScore;
    }
    public Integer getBoneScore() {
        return this.boneScore;
    }
    
    public void setBoneScore(Integer boneScore) {
        this.boneScore = boneScore;
    }
    public Integer getBodyScore() {
        return this.bodyScore;
    }
    
    public void setBodyScore(Integer bodyScore) {
        this.bodyScore = bodyScore;
    }
    public Integer getHeadScore() {
        return this.headScore;
    }
    
    public void setHeadScore(Integer headScore) {
        this.headScore = headScore;
    }
    public Integer getCleverScore() {
        return this.cleverScore;
    }
    
    public void setCleverScore(Integer cleverScore) {
        this.cleverScore = cleverScore;
    }
    public Dog getDog() {
        return this.dog;
    }
    
    public void setDog(Dog dog) {
        this.dog = dog;
    }




}


